# Generated by Django 4.1 on 2022-08-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_word', models.CharField(max_length=500)),
                ('max_len', models.IntegerField()),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
    ]
