# Generated by Django 4.1 on 2022-08-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_textgenerator_max_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textgenerator',
            name='max_len',
            field=models.IntegerField(null=True),
        ),
    ]
