# Generated by Django 4.1 on 2022-08-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_textgenerator_max_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='textgenerator',
            name='text',
            field=models.CharField(default='aaa', max_length=10000),
            preserve_default=False,
        ),
    ]
