# Generated by Django 4.1 on 2022-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_textgenerator_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textgenerator',
            name='init_word',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='textgenerator',
            name='max_len',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
