# Generated by Django 4.1 on 2022-08-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_textgenerator_init_word_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextGenerator',
            new_name='TextGeneratorApp',
        ),
    ]
