# Generated by Django 4.1 on 2022-08-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textgenerator',
            name='max_len',
        ),
        migrations.RemoveField(
            model_name='textgenerator',
            name='text',
        ),
    ]
