# Generated by Django 4.1 on 2022-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_textgenerator_max_len_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textgenerator',
            name='max_len',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
